=== alexmarder/bdrmapit/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "The arguments to run bdrmapIT",
  "type": "object",
  "properties": {
    "ip2as": {
      "description": "Filename of prefix-to-AS mappings in CAIDA prefix2as format",
      "type": "string"
    },
    "as2org": {
      "type": "object",
      "properties": {
        "as2org": {
          "description": "CAIDA AS2Org filename",
          "type": "string"
        },
        "additional": {
          "description": "Filename with additional siblings",
          "type": "string"
        }
      },
      "required": ["as2org"]
    },
    "as-rels": {
      "description": "AS relationship inferences from CAIDA",
      "type": "object",
      "properties": {
        "rels": {
          "description": "The relationship file that indicates provider or peer relationships",
          "type": "string"
        },
        "cone": {
          "description": "The customer cone file",
          "type": "string"
        }
      },
      "required": ["rels", "cone"]
    },
    "warts": {
      "description": "Warts traceroute files, such as those created by scamper",
      "type": "object",
      "properties": {
        "files": {
          "description": "File with traceroute files, newline separated",
          "type": "string"
        },
        "files-list": {
          "description": "List of traceroute filenames",
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    },
    "atlas": {
      "description": "Warts traceroute files, such as those created by scamper",
      "type": "object",
      "properties": {
        "file-list": {
          "description": "File with traceroute files, newline separated",
          "type": "string"
        },
        "files": {
          "description": "List of traceroute filenames",
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    },
    "aliases": {
      "description": "Alias resolution file in CAIDA ITDK format",
      "type": "string"
    },
    "processes": {
      "type": "integer",
      "default": 2
    }
  },
  "required": ["ip2as", "as2org", "as-rels"]
}

=== alexmarder/bdrmapit/test.json
{
  "$schema": "schema.json",
  "ip2as": "../ip2as/test.csv",
  "as2org": {
    "as2org": "../retrieve-external/orgs/20181001.as-org2info.txt.gz"
  },
  "as-rels": {
    "rels": "../retrieve-external/rels/20180801.as-rel.txt.bz2",
    "cone": "../retrieve-external/rels/20180801.ppdc-ases.txt.bz2"
  },
  "warts": {
    "files": "warts.files"
  },
  "processes": 3
}
